# wikmd configuration file

wikmd_host: "0.0.0.0"
wikmd_port: 5000
wikmd_logging: 1
wikmd_logging_file: "wikmd.log"

git_user: "wikmd"
git_email: "wikmd@no-mail.com"

main_branch_name: "main"
sync_with_remote: 0
remote_url: ""

wiki_directory: "wiki"
images_route: "img"
homepage: "homepage.md"
homepage_title: "homepage"

protect_edit_by_password: 0
password_in_sha_256: "0E9C700FAB2D5B03B0581D080E74A2D7428758FC82BD423824C6C11D6A7F155E" #ps: wikmd 

local_mode: false
